# docker-compose.bot.yml - Solo el bot de Telegram
version: '3.8'

services:
  nas-photo-bot:
    build: ./bot
    container_name: ${CONTAINER_NAME:-nas-photo-bot}
    env_file:
      - .env
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_USER_ID: ${TELEGRAM_USER_ID}
      TZ: ${TZ:-Europe/Madrid}
      UMASK: "002"
    volumes:
      - ${HOST_DATA_PATH}:${DATA_PATH:-/data/fotos}
    restart: unless-stopped
    # Configuración optimizada para NAS con poca RAM
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.2'
    # Configuración de logging para reducir I/O
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # No crear red si no es necesario (usa red por defecto)
    network_mode: bridge
